language: python
dist: xenial
python:
  - "3.6.7"
before_install:
    - sudo apt-get -o Acquire::https::No-Cache=True -o Acquire::http::No-Cache=True update -qq
    - sudo apt-get install python-bluetooth -qq -y
    - pip install pyserial==3.1.1
    - pip install coveralls
install: pip install -q -e .
script: python setup.py test
after_success:
  - coverage run --source=openxc setup.py test
  - coveralls
before_deploy:
  - cd ..
  - tar -zcf ${REPO}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-SourceCode.tar.gz ${REPO}
  - zip -r ${REPO}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}-SourceCode.zip ${REPO}
deploy:
  provider: pypi
  server: https://pypi.org/legacy/
  user: "__token__"
  password: $PYPI_PASSWORD
  on:
    branch: master
