language: python
dist: xenial
python:
  - "3.6.7"
before_install:
    - sudo apt-get -o Acquire::https::No-Cache=True -o Acquire::http::No-Cache=True update -qq
    - sudo apt-get install python-bluetooth -qq -y
    - pip install pyserial==3.1.1
    - pip install coveralls
install: pip install -q -e .
script: python setup.py test
after_success:
  - coverage run --source=openxc setup.py test
  - coveralls
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: "__token__"
  password: "pypi-AgENdGVzdC5weXBpLm9yZwIkMmU2YTdiOWYtMGMzOC00OTY1LTgxYjItMWEzY2M2MjQyZDg1AAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiCin-LheY5ZIhBODVnZEorzIlP5W45FX0lM4FjteHO8zw"
  on:
    all_branches: true
